import './globals.css'
import Link from "next/link";

export const metadata = {
  title: 'Home page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <nav>
        <Link href={'/ssr'}>Go to SSR</Link>
          <br/>
        <Link href={'/csr'}>Go to CSR</Link>
      </nav>
      {children}
      </body>
    </html>
  )
}
